[project]
name = "nanobanana"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastmcp>=2.12.5",
    "google-genai>=1.45.0",
    "python-dotenv>=1.1.1",
]
